# Generated by Django 4.2.6 on 2023-11-04 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitorear', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planta',
            name='precio',
        ),
    ]
