# Generated by Django 4.2.6 on 2023-11-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorear', '0002_remove_planta_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planta',
            name='Imagen',
        ),
        migrations.AddField(
            model_name='planta',
            name='condicionAmbiental',
            field=models.TextField(default='av'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planta',
            name='origen',
            field=models.CharField(default='at', max_length=70),
            preserve_default=False,
        ),
    ]
